# ---------- BUILD STAGE ----------
FROM node:20-alpine AS build

WORKDIR /app

# install deps
COPY package.json package-lock.json ./
RUN npm install

# copy source
COPY . .

# 🔥 THIS IS THE FIX
RUN npm run build

# ---------- PRODUCTION STAGE ----------
FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
